Autoveille/Controllers/RapportsController.cs
using Autoveille.TestingModels;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Autoveille.Controllers
{
    public class RapportsController : Controller
    {
        // GET: Rapports
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult EvenementParFabricant()
        {
            List<ConcessionnaireParFabricant> concessions = new List<ConcessionnaireParFabricant>
            {
                new ConcessionnaireParFabricant
                {
                    Id=0,
                    NomConcessionnaire="Nom Concessionnaire",
                    DateEvenement = "du 00 au 00 mois 2021"
                },
                new ConcessionnaireParFabricant
                {
                    Id=1,
                    NomConcessionnaire="Nom Concessionnaire",
                    DateEvenement = "du 00 au 00 mois 2021"
                },

                new ConcessionnaireParFabricant
                {
                    Id = 2,
                    NomConcessionnaire = "Nom Concessionnaire",
                    DateEvenement = "du 00 au 00 mois 2021"
                },

                new ConcessionnaireParFabricant
                {
                    Id=3,
                    NomConcessionnaire="Nom Concessionnaire",
                    DateEvenement = "du 00 au 00 mois 2021"
                },
                new ConcessionnaireParFabricant
                {
                    Id = 4,
                    NomConcessionnaire = "Nom Concessionnaire",
                    DateEvenement = "du 00 au 00 mois 2021"
                },
            };

            return PartialView(concessions);
        }

        public ActionResult EvenementAvenirParFabricant()
        {
            List<ConcessionnaireParFabricant> concessions = new List<ConcessionnaireParFabricant>
            {
                new ConcessionnaireParFabricant
                {
                    Id=0,
                    NomConcessionnaire="Nom Concessionnaire",
                    DateEvenement = "du 00 au 00 mois 2021"
                },
                new ConcessionnaireParFabricant
                {
                    Id=1,
                    NomConcessionnaire="Nom Concessionnaire",
                    DateEvenement = "du 00 au 00 mois 2021"
                },

                new ConcessionnaireParFabricant
                {
                    Id = 2,
                    NomConcessionnaire = "Nom Concessionnaire",
                    DateEvenement = "du 00 au 00 mois 2021"
                },

                new ConcessionnaireParFabricant
                {
                    Id=3,
                    NomConcessionnaire="Nom Concessionnaire",
                    DateEvenement = "du 00 au 00 mois 2021"
                },
                new ConcessionnaireParFabricant
                {
                    Id = 4,
                    NomConcessionnaire = "Nom Concessionnaire",
                    DateEvenement = "du 00 au 00 mois 2021"
                },
            };

            return PartialView(concessions);
        }

        public ActionResult RapportsEvenementEnCours()
        {
            return PartialView();
        }
        [HttpPost]
        public JsonResult allComparateur(List<int> checkedEvents) 
        {
            TempData["checkedEvents"] = checkedEvents;
            return Json("successfully transported check events ids",JsonRequestBehavior.AllowGet);
        }

        public ActionResult Comparateur()
        {
            var checkedEvents = TempData["checkedEvents"] as List<int>;
            if (checkedEvents != null)
            {
                List<Dashboard> dashboards = new List<Dashboard>();
                foreach (int i in checkedEvents)
                {
                    dashboards.Add(new Dashboard { IdEvenement = i, WalkIn = 50, DateEvenement = new DateTime(2020 / 12 / 10), Oportunites = 10, Potentiels = 20, RDV = 15, Ventes = 12 });
                }
                return View(dashboards);
            }
            return View("selectionnerEvents");
        }

        public ActionResult selectionnerEvents()
        {
            return View();
        }

        public ActionResult Rapports_PartialCurrentEvent(int eventId)
        {
            var dashboard = new Dashboard()
            {
                IdEvenement = eventId,
                RDV = 24,
                Ventes = 15,
                Oportunites = 94,
                Potentiels = 300,
                WalkIn = 32,
            };
            return PartialView(dashboard);
        }
    }
}

Autoveille/Views/Rapports/Comparateur.cshtml
@model IEnumerable<Autoveille.TestingModels.Dashboard>
    @{
        ViewBag.Title = "Comparateur";
        Layout = "~/Views/Shared/_LayoutBlack.cshtml";
    }
    <div style="display:flex;justify-content:center;">
        <button style="margin:auto;width:20vw; border-radius:15px;color:white;" class="btn btn-danger" onclick="Telecharger()">Télécharger</button>
    </div>
    <div class="rootContainer" style="display:flex;flex-direction:column;">
        <div style="display:flex;width:100%;flex-wrap:wrap;">
            @foreach (var item in Model)
            {
                <div class="OneDash" style="width:50%; height:auto;">
                    <div style="margin:15px;">
                        <p style="color:white;font-size:2.5em;">Nom du Concessionnaire</p>
                        <p style="color:white;font-size:2.5em;"> 00 au 00 mois 2021</p>
                    </div>
                    @{

                        Html.RenderAction("Rapports_PartialCurrentEvent", "Rapports", new { eventId = item.IdEvenement });
                    }
                </div>
                @*<div style="width:50%;">
                            <div style="margin:15px;">
                                <p style="color:white;font-size:2.5em;">Nom du Concessionnaire</p>
                                <p style="color:white;font-size:2.5em;"> 00 au 00 mois 2021</p>
                            </div>
                            @{
                                Html.RenderAction("Rapports_PartialCurrentEvent", "Rapports", new { eventId = 2 });
                            }
                        </div>
                        <div style="width:50%;">
                            <div style="margin:15px;">
                                <p style="color:white;font-size:2.5em;">Nom du Concessionnaire</p>
                                <p style="color:white;font-size:2.5em;"> 00 au 00 mois 2021</p>
                            </div>
                            @{
                                Html.RenderAction("Rapports_PartialCurrentEvent", "Rapports", new { eventId = 3 });
                            }
                        </div>
                        <div style="width:50%;">
                        <p style="color:white;font-size:2.5em;">Nom du Concessionnaire</p>
                        <p style="color:white;font-size:2.5em;"> 00 au 00 mois 2021</p>
                        @{
                            Html.RenderAction("Rapports_PartialCurrentEvent", "Rapports", new { eventId = 4 });
                        }
                    </div>*@

            }
        </div>
    </div>


    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/chartjs-plugin-datalabels/0.7.0/chartjs-plugin-datalabels.min.js"></script>*@
    @*<script src="~/Scripts/MyScripts/Rapports_PartialCurrentEvent.js"></script>*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.4/jspdf.min.js"></script>
    <script>
        //var  setUpCanvas = (c) => {
        //     c.width = c.clientWidth;
        //     c.height = c.clientHeight;
        // };
        var id = 0;
        var hhh;

        $(document).ready(function () {
            hhh = $('.OneDash').height();
            console.log(hhh);
        });

        function Telecharger() {
            //console.log(dashId);
            //html2canvas($('.rootContainer'), { scrollY: -window.scrollY }) //#barsContainer  mainCurrentRow
            //    .then(function (canvas) {
            //        var imgData = canvas.toDataURL('image/png');
            //        var doc = new jsPDF({ orientation: 'p', format: 'a1' });
            //        var options = { pagesplit: true };
            //        var width = doc.internal.pageSize.width;
            //        var height = doc.internal.pageSize.height;
            //        doc.addImage(imgData, 'PNG', 0, 0,width,height);
            //        doc.save('sample-file.pdf');
            //    }
            //    );

            var HTML_Width = $(".rootContainer").width();
            var HTML_Height = $(".rootContainer").height();
            var top_left_margin = 15;
            var PDF_Width = HTML_Width + (top_left_margin * 2);
            var PDF_Height = hhh;//(PDF_Width * 1.5) + (top_left_margin * 2);
            var canvas_image_width = HTML_Width;
            var canvas_image_height = HTML_Height;

            var totalPDFPages = Math.ceil(HTML_Height / PDF_Height) - 1;

            html2canvas($(".rootContainer")[0], { allowTaint: true }).then(function (canvas) {
                canvas.getContext('2d');

                console.log(canvas.height + "  " + canvas.width);


                var imgData = canvas.toDataURL("image/jpeg", 1.0);
                var pdf = new jsPDF('p', 'pt', [PDF_Width, hhh]);
                pdf.addImage(imgData, 'JPG', top_left_margin, top_left_margin, canvas_image_width, canvas_image_height);


                for (var i = 1; i <= totalPDFPages; i++) {
                    pdf.addPage(PDF_Width, PDF_Height);
                    pdf.addImage(imgData, 'JPG', top_left_margin, -(PDF_Height * i) /*+ (top_left_margin * 4)*/, canvas_image_width, canvas_image_height);
                }

                pdf.save("HTML-Document.pdf");
            });

        }
    </script>

Autoveille/Views/Rapports/EvenementAvenirParFabricant.cshtml
@model IEnumerable<Autoveille.TestingModels.ConcessionnaireParFabricant>

    <div id="searchDiv" style="width:100%;display:flex;flex-direction:row;margin-bottom:10px;">
        <div style="width: 50%;display:flex;">
            <i class="fas fa-search fa-3x iconSearch"></i>
            <input class="InputRecherche" type="search" placeholder="| Recherche par nom du concessionnaire" />
        </div>
        <div style="width:50%;display:flex;flex-direction:row;">
            <i class="fas fa-search fa-3x iconSearch"></i>
            <input class="InputRecherche" type="search" placeholder="| Recherche par nom du date" />
        </div>
    </div>

    <table class="table appelsTable" style="width:100%;">
        @foreach (var item in Model)
        {
            var rowId = "row" + item.Id;
            var dashboardsId = "dashboards" + item.Id;
            var imgId = "img" + item.Id;

            <tr id="@rowId" style="background-color:#fbbb29;height:70px;margin-bottom:5px;color:#160F0C;text-align:center;padding-top:20px;">
                <td>
                    <img id="@imgId" src="~/Content/Images/Layout/Plus.png" width="30" height="30" alt="Plus button Logo" onclick="displayDashboard(@item.Id )" role="button">
                </td>
                <td class="appels-td">
                    @Html.DisplayFor(modelItem => item.NomConcessionnaire)
                </td>
                <td class="appels-td">
                    @Html.DisplayFor(modelItem => item.DateEvenement)
                    <label style="float:right;">
                        <input type="checkbox" name="checkEvent" value="@item.Id">
                        <span>     </span>
                    </label>
                    @*<input class="custom-checkbox" style="border-color:black;display:block;float:right;" checked="checked" type="checkbox" name="concessionCheck" value="@item.Id" />*@
                </td>

            </tr>
            <tr>
                <td id="@dashboardsId" colspan="3" style="display:none;padding:0;">
                </td>
            </tr>
        }

    </table>


    <script>
        var idConcession;


        function displayDashboard(IdConcessionnaire) {
            if (idConcession === undefined) {
                idConcession = IdConcessionnaire;
            }
            else if (idConcession != IdConcessionnaire) {
                hideDashboard(idConcession);
                idConcession = IdConcessionnaire;
            }


            $.ajax({
                url: '../Rapports/RapportsEvenementEnCours/',
                contentType: 'application/html; charset=utf-8',
                type: 'GET',
                data: { IdConcessionnaire: IdConcessionnaire },
                dataType: 'html',
                success: function (result) {
                    var dashboardsId = "dashboards" + IdConcessionnaire;
                    var imgId = "img" + IdConcessionnaire;
                    $('#' + dashboardsId).html(result);
                    //$('#' + dashboardsId).toggle();
                    $('#' + dashboardsId).css("display", "");
                    $('#' + imgId).attr('onclick', 'hideDashboard(' + IdConcessionnaire + ')');
                    $('#' + imgId).attr('src', '../Content/Images/Layout/Moins.png');
                },
                error: function (xhr, status) {
                    alert(status);
                }
            });
        }

        function hideDashboard(IdConcessionnaire) {
            //$('#detailsClient').css('visibility', 'hidden');
            var dashboardsId = "dashboards" + IdConcessionnaire;
            var imgId = "img" + IdConcessionnaire;
            $('#' + imgId).attr('onclick', 'displayDashboard(' + IdConcessionnaire + ')');
            $('#' + imgId).attr('src', '../Content/Images/Layout/Plus.png');
            //$('#' + dashboardsId).toggle();
            $('#' + dashboardsId).css("display", "none");
            $('#' + dashboardsId).empty();


            //if (myBar) {
            //    myBar.destroy();
            //}
        }


        function saveAsPdf(dashId) {
            console.log(dashId);
            html2canvas($(dashId), { scrollY: -window.scrollY }) //#barsContainer  mainCurrentRow
                .then(function (canvas) {
                    var imgData = canvas.toDataURL('image/png');
                    var doc = new jsPDF({ orientation: 'l', format: 'a5' });

                    var width = doc.internal.pageSize.width;
                    var height = doc.internal.pageSize.height;
                    doc.addImage(imgData, 'PNG', 0, 0, width, height);
                    doc.save('sample-file.pdf');
                }
                );
        }



        $(document).ready(function () {


            $('input:checkbox').click(function (e) {
                console.clear();
                var $box = $(this);
                //console.log($box.is(":checked"));
                var checkedCheckBoxes = $('input:checkbox:checked').length;
                if (checkedCheckBoxes > 0) {
                    var firstCheckedRow = $('input:checkbox:checked')[0].value;
                }
                else {
                    $(".downloadIcon").css("color", "grey");
                }

                if (checkedCheckBoxes == 1) {
                    $(".downloadIcon").css("color", "white");
                    var finalElement = $('#AfficherConcessionnairesAvenir input:checked')[0].value;
                    if ($("dashboards" + finalElement).length == 0) {
                        console.log("let's show it");
                        displayDashboard(finalElement);
                    }

                    $('.comparButton').prop("disabled", "true");
                    //console.log('#dashboards' + finalElement);
                    $(".downloadIcon").click(function () { saveAsPdf('#dashboards' + finalElement) });
                }
                else if (checkedCheckBoxes != 0) {
                    hideDashboard(firstCheckedRow);
                    $(".downloadIcon").css("color", "grey");
                    $('.comparButton').prop("disabled", false);
                }
                console.log(firstCheckedRow);
                if ($box.is(":checked")) {


                } else {
                    $box.prop("checked", false);
                    //console.log($box.val());
                    hideDashboard($box.val());
                }



            });

        });

    </script>

Autoveille/Views/Rapports/EvenementParFabricant.cshtml
@model IEnumerable<Autoveille.TestingModels.ConcessionnaireParFabricant>

    <div id="searchDiv" style="width:100%;display:flex;flex-direction:row;margin-bottom:10px;">
        <div style="width: 50%;display:flex;">
            <i class="fas fa-search fa-3x iconSearch"></i>
            <input class="InputRecherche" type="search" placeholder="| Recherche par nom du concessionnaire" />
        </div>
        <div style="width:50%;display:flex;flex-direction:row;">
            <i class="fas fa-search fa-3x iconSearch"></i>
            <input class="InputRecherche" type="search" placeholder="| Recherche par nom du date" />
        </div>
    </div>

    <table class="table appelsTable" style="width:100%;">
        @foreach (var item in Model)
        {
            var rowId = "row" + item.Id;
            var dashboardsId = "dashboards" + item.Id;
            var imgId = "img" + item.Id;

            <tr id="@rowId" style="background-color:#fbbb29;height:70px;margin-bottom:5px;color:#160F0C;text-align:center;padding-top:20px;">
                <td>
                    <img id="@imgId" src="~/Content/Images/Layout/Plus.png" width="30" height="30" alt="Plus button Logo" onclick="displayDashboard(@item.Id )" role="button">
                </td>
                <td class="appels-td">
                    @Html.DisplayFor(modelItem => item.NomConcessionnaire)
                </td>
                <td class="appels-td">
                    @Html.DisplayFor(modelItem => item.DateEvenement)
                    <label style="float:right;">
                        <input type="checkbox" name="checkEvent" value="@item.Id">
                        <span>     </span>
                    </label>
                    @*<input class="custom-checkbox" style="border-color:black;display:block;float:right;" checked="checked" type="checkbox" name="concessionCheck" value="@item.Id" />*@
                </td>

            </tr>
            <tr>
                <td id="@dashboardsId" colspan="3" style="display:none;padding:0;">
                </td>
            </tr>
        }

    </table>

    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.4/jspdf.min.js"></script>*@
    <script>
        var idConcession;
        var checkedEvents;

        function displayDashboard(IdConcessionnaire) {
            console.log("consess   : " + idConcession);
            if (idConcession === undefined) {
                idConcession = IdConcessionnaire;
            }
            else if (idConcession != IdConcessionnaire) {
                hideDashboard(idConcession);
                idConcession = IdConcessionnaire;
            }


            $.ajax({
                url: '../Rapports/RapportsEvenementEnCours/',
                contentType: 'application/html; charset=utf-8',
                type: 'GET',
                data: { IdConcessionnaire: IdConcessionnaire },
                dataType: 'html',
                success: function (result) {
                    var dashboardsId = "dashboards" + IdConcessionnaire;
                    var imgId = "img" + IdConcessionnaire;
                    $('#' + dashboardsId).html(result);
                    //$('#' + dashboardsId).toggle();
                    $('#' + dashboardsId).css("display", ""); //  = ('#' + dashboardsId).css("display") == "none" ? '' : 'none';
                    $('#' + imgId).attr('onclick', 'hideDashboard(' + IdConcessionnaire + ')');
                    $('#' + imgId).attr('src', '../Content/Images/Layout/Moins.png');
                },
                error: function (xhr, status) {
                    alert(status);
                }
            });
        }

        function hideDashboard(IdConcessionnaire) {
            //$('#detailsClient').css('visibility', 'hidden');
            var dashboardsId = "dashboards" + IdConcessionnaire;
            var imgId = "img" + IdConcessionnaire;
            $('#' + imgId).attr('onclick', 'displayDashboard(' + IdConcessionnaire + ')');
            $('#' + imgId).attr('src', '../Content/Images/Layout/Plus.png');
           // $('#' + dashboardsId).toggle();
            $('#' + dashboardsId).css("display", "none"); 
            $('#' + dashboardsId).empty();


            //if (myBar) {
            //    myBar.destroy();
            //}
        }

        function saveAsPdf(dashId) {
            console.log(dashId);
            html2canvas($(dashId), { scrollY: -window.scrollY }) //#barsContainer  mainCurrentRow
                .then(function (canvas) {
                    var imgData = canvas.toDataURL('image/png');
                    var doc = new jsPDF({ orientation: 'l', format: 'a5' });

                    var width = doc.internal.pageSize.width;
                    var height = doc.internal.pageSize.height;
                    doc.addImage(imgData, 'PNG', 0, 0, width, height);
                    doc.save('sample-file.pdf');
                }
                );
        }



        $(document).ready(function () {


            $('input:checkbox').click(function (e) {
                console.clear();
                var $box = $(this);
                //console.log($box.is(":checked"));
                var checkedCheckBoxes = $('input:checkbox:checked').length;
                if (checkedCheckBoxes > 0) {
                    var firstCheckedRow = $('input:checkbox:checked')[0].value;
                    checkedEvents = [];
                    $('input:checkbox:checked').each(function () {
                        checkedEvents.push($(this).val());
                    })
                   // console.log("checked events : " + checkedEvents);
                }
                else {
                    $(".downloadIcon").css("color", "grey");                }
               
                if (checkedCheckBoxes == 1) {
                    $(".downloadIcon").css("color", "white");
                    var finalElement = $('#AfficherConcessionnairesEnCours input:checked')[0].value;
                    if ($("dashboards" + finalElement).length == 0) {
                        console.log("let's show it");
                        displayDashboard(finalElement);
                    }
                    
                    $('.comparButton').prop("disabled", "true");
                    //console.log('#dashboards' + finalElement);
                    $(".downloadIcon").click(function () { saveAsPdf('#dashboards' + finalElement) });
                }
                else if (checkedCheckBoxes !=0) {
                    hideDashboard(firstCheckedRow);
                    $(".downloadIcon").css("color", "grey");
                    $('.comparButton').prop("disabled", false);
                }
                console.log(firstCheckedRow);
                if ($box.is(":checked")) {


                } else {
                    $box.prop("checked", false);
                    //console.log($box.val());
                    hideDashboard($box.val());
                }



            });

        });





    </script>

Autoveille/Views/Rapports/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutBlack.cshtml";
}



@{
    ViewBag.Title = "TableauDeBordDesFabicants";
    Layout = "~/Views/Shared/_LayoutBlack.cshtml";
}


<div class="row alertRow" id="eventDiv" style="height:35px;">
    <div style="float:left;display:flex;" class="col-md-3 col-sm-12 col-xs-12">
        <a class="eventText" id="enCours" style="color: white;" onclick="AfficherLesConcessionnairesEnCours()">
            Evenement en cours
        </a>
    </div>
    <div style="float:left;display:flex;justify-content:center" class="col-md-3 col-sm-12 col-xs-12">
        <a class="eventText" id="aVenir" style="color: white;" onclick="AfficherLesConcessionnairesAvenir()">
            Evenement a venir
        </a>
    </div>
    <div class="eventText col-md-3 col-sm-12 col-xs-12">
        <i class="fas fa-download downloadIcon" style="color:grey;"></i>
    </div>
    <div id="searchInput" class="eventText col-md-3 col-sm-12 col-xs-12" style="color:white;display:flex;flex-flow:row-reverse;">
        Nom du concessionnaire
    </div>
</div>
<br />

<div class="comparDiv" style="color:white;display:flex;margin:auto;width:95%;">
    <div style="width:50%;">
        <p>
            <span class="boldText" style="font-weight:bold;font-size:2.5em;">Comparateur d'événements</span> <br />
            <span class="normalText" style="font-size:1.5em;">Cochez, à droite, les évènements à comparer </span>
        </p>
    </div>
    <div style="width:50%;margin:auto;">
        <button class="btn btn-danger comparButton" disabled style="width:20rem;height:3.5em;border-radius:10px;" onclick="compareEvents()">Comparer</button>
    </div>
</div>
<div id="AfficherConcessionnairesEnCours" style="margin:auto;width:95%;">

</div>
<div id="AfficherConcessionnairesAvenir" style="margin:auto;width:95%;display:none;">

</div>


<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/chartjs-plugin-datalabels/0.7.0/chartjs-plugin-datalabels.min.js"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.4/jspdf.min.js"></script>
<script>
    $(function () {
        AfficherLesConcessionnairesEnCours();
    });


    function AfficherLesConcessionnairesEnCours() {
        $('#AfficherConcessionnairesAvenir').css('display', 'none');
        $('#AfficherConcessionnairesAvenir').empty();
        $.ajax({
            url: "/Rapports/EvenementParFabricant/"
        }).done(function (data) {
            $("#AfficherConcessionnairesEnCours").html(data);
        });
        $('#AfficherConcessionnairesEnCours').css('display', 'block');
        $("#aVenir").removeClass("activeNav");
        $("#enCours").addClass("activeNav");
    }

    function AfficherLesConcessionnairesAvenir() {
        $('#AfficherConcessionnairesEnCours').css('display', 'none');
        $('#AfficherConcessionnairesEnCours').empty();
        $.ajax({
            url: "/Rapports/EvenementAvenirParFabricant/"
        }).done(function (data) {
            $("#AfficherConcessionnairesAvenir").html(data);
        });
        $('#AfficherConcessionnairesAvenir').css('display', 'block');
        $("#aVenir").addClass("activeNav");
        $("#enCours").removeClass("activeNav");
    }

    function compareEvents() {
        @*var aa = JSON.stringify({ checkedEvents });
        var url = '@Url.Action("Comparateur", "Rapports", new { checkedEvents = "aa" })';
        console.log(aa);
        window.location.href = url.replace('aa', aa);*@


        $.ajax({
            url: '@Url.Action("allComparateur")',
            type: 'POST',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({ checkedEvents }),
            dataType: "json",
            success: function () {
               // console.log('redirect');
                var url = '@Url.Action("Comparateur", "Rapports")';
                window.location.href = url;
            },
            error: function () {
                alert("impossible de lancer la comparaison");
            }
        })
    }





    //chartColors = {
    //    red: 'rgb(255, 99, 132)',
    //    orange: 'rgb(255, 1UrlAuthorizationModule9, 64)',
    //    yellow: 'rgb(255, 205, 86)',
    //    green: 'rgb(75, 192, 192)',
    //    blue: 'rgb(54, 162, 235)',
    //    purple: 'rgb(153, 102, 255)',
    //    grey: 'rgb(231,233,237)'
    //};

     setUpCanvas = (c) => {
        c.width = c.clientWidth;
        c.height = c.clientHeight;
    };
</script>

Autoveille/Views/Rapports/selectionnerEvents.cshtml
@{
    ViewBag.Title = "selectionnerEvents";
    Layout = "~/Views/Shared/_LayoutBlack.cshtml";
}
<div style="margin-top:15vh;display:flex;flex-direction:column;">
    <h2 style="text-align:center;color:white;">Veuillez sélectionner des evenements pour les comparer </h2>
    <button class="btn btn-danger" style="color:white;border-radius:15px;width:15vw;margin:auto;" onclick="location.href='@Url.Action("index","Rapports")'"> Sélectionner des évènements</button>
</div>