Autoveille/Controllers/CompteController.cs
using Autoveille.Models;
using AutoveilleBL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Autoveille.Controllers
{
    public class CompteController : BaseController
    {

        public ActionResult EnregistrerUtilisateur()
        {
            return View();
        }


        //
        // GET: /Compte/

        public ActionResult Connexion()
        {
            return View();
        }


        //public ActionResult Connexion(LoginModel model)
        //{
        //    return View();
        //}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Connexion(LoginModel model, string returnUrl)
        {
            if (Authenticate(model.UserName, model.Password, false))
            {
                return RedirectToLocal("");
            }

            return View(model);
        }


        public JsonResult sendPassword()
        {
            return Json("True", JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult ModifierMotDePasse()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ModifierMotDePasse(string newPassword)
        {
            return View();
        }
        public ActionResult MotDePasseOubliee()
        {
            return View();
        }

        #region LogOff

        //
        // POST: /Compte/LogOff

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            SignOut();
            return RedirectToAction("Index", "Home");
        }

        #endregion

        #region Private methods
        private void SetAuthenticationCookie(string aUser, int aUserId, bool isCookiePersistent)
        {
            //Login was successful, create FormsAuthentication ticket.
            System.Web.Security.FormsAuthenticationTicket authTicket = new System.Web.Security.FormsAuthenticationTicket(1, aUser, DateTime.Now, DateTime.Now.AddMinutes(30), isCookiePersistent, aUserId.ToString());

            //Encrypt the cookie
            HttpCookie cookie = new HttpCookie(System.Web.Security.FormsAuthentication.FormsCookieName, System.Web.Security.FormsAuthentication.Encrypt(authTicket));

            //NOTE: You ABSOLUTELY MUST add() the cookie to the cookies collection in order for the User.Identity.IsAuthenticated to return TRUE.
            //      If you do not add() to the cookies collection, the User.Identity.IsAuthenticated will always return FALSE.
            Response.Cookies.Add(cookie);
        }

        private bool Authenticate(string username, string password, bool rememberMe)
        {
            //bool result = (username == "test" && password == "test");
            bool result = Utilisateurs.ValidateUtilisateurGroupe(username, password);
            if (result)
            {
                var utilisateur = Utilisateurs.GetUtilisateurFromAlias(username);
                var commerceSite = Utilisateurs.GetUtilisateurCommerceFromAlias(username);

                var nom = String.IsNullOrEmpty(utilisateur.FirstName) && String.IsNullOrEmpty(utilisateur.LastName) ?
                   username
                    : utilisateur.FirstName + " " + utilisateur.LastName;

                Session["Commerces"] = commerceSite;
                Session["Email"] = utilisateur.Email;
                Session["User"] = utilisateur.UserName;
                Session["UserId"] = utilisateur.UserID;
                Session["FirstName"] = utilisateur.FirstName;
                Session["LastName"] = utilisateur.LastName;
                Session["Nom"] = nom;
                Session["Role"] = utilisateur.Role.ToString();
                Session["Type"] = utilisateur.TypeUsager.ToString();

                SetAuthenticationCookie(username, 1, rememberMe);
            }

            return result;
        }



        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                 return RedirectToAction("InfoConcession", "Home");              
            }
        }

        #endregion


    }
}

Autoveille/Views/Compte/Connexion.cshtml
@model Autoveille.Models.LoginModel
@{
    ViewBag.Title = "Connexion";
}

<style>
    body {
        background-color: #fbbb29;
    }

    .btn-submit {
        border: none;
        background: #EE1D29;
        color: #fff;
        text-transform: uppercase;
        border-radius: 5px;
        font-size: 12px;
        font-family: proxima-nova;
        text-align: center;
        padding: 0px 0;
        width: 100%;
        height: 28px;
        margin: 0px 0 0px 0;
        cursor: pointer;
    }


    .form-text {
        padding: 1px 1px 1px 1px;
        border-radius: 5px;
        border: 1px solid #e6e6e6;
        width: 100%;
        height: 25px;
        margin: 3px 0;
        font-size: 12px;
        font-weight: bold;
        color: black;
        background-color: white;
        padding-left: 10px;
    }


    .form-pass {
        background-color: white;
        /*width:200px;*/
    }


    /*.form-text:focus
        {background-color:#FFFEE6; color:#cccccc; border: 2px solid #8C151B;}
    section#loginForm {width: 310px; margin: 0 auto;}

        a.basFieldset {color:#8C151B; text-decoration: none; font-weight: bold;font-size: 12px}
        a.basFieldset:hover {color:#3F3F40; text-decoration: none; font-weight: bold;font-size: 12px} */
</style>
<div class="row">
    <div class="col-12 col-sm-12 col-md-1 col-lg-3">
    </div>
    <div class="col-12 col-sm-12 col-md-10 col-lg-6">
        <div style="background-color:#fbbb29;padding-top:10px;padding-left:60px;
            padding-right:60px; height:350px">

            <section id="loginForm" style="margin: 0 auto;height:347px;">

                @using (Html.BeginForm("Connexion", "Compte", new { ReturnUrl = Request.QueryString["ReturnUrl"] }, FormMethod.Post, new { role = "form" }))
                {

                    <div class="boxe" style="padding:30px;text-align: center;">
                        <div>
                            <div>
                                <span style="text-align: center;color:white;font-size:19px;text-align:center">Bienvenue sur le portail autoveille,</span>
                                <br />
                                <span style="text-align: center;color:white;font-size:19px;text-align:center">votre gestionnaire d'opportunités</span>
                            </div>
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div style="display:flex;flex-direction:column;">

                                <b style="text-align:center;font-size:14px;padding-top:15px;padding-bottom:5px">Identifiez-vous!</b>
                                <div class="center">
                                    @Html.TextBoxFor(m => m.UserName, new
                                    {
                                        @class = "form-text",
                                        placeholder = "Votre nom d'utilisateur"

                                    })
                                    @Html.ValidationMessageFor(m => m.UserName, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div>
                                @*@Html.LabelFor(m => m.Password, new {@class = "control-label"})*@
                                <div class="center">
                                    @Html.PasswordFor(m => m.Password, new
                                    {
                                        @class = "form-text form-pass",
                                        placeholder = "Votre mot de passe"
                                    })
                                    @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div>
                                <div style="text-align:center;" class="btn-center">
                                    <input style="padding-bottom:5px;padding-top:5px;" type="submit" value="S'identifier" class="btn btn-info btn-submit " />
                                    <div style="padding-top:10px;margin-bottom:0px">
                                        <input type="checkbox" id="checkSouviensDeMoi" name="connexionCheckBox" value="true"
                                               style="display:inline-block;padding-top:10px;vertical-align:top">
                                        <label style="font-size:12px;vertical-align:top;padding-top:0px" for="checkSouviensDeMoi">Se souvenir de moi </label>
                                    </div>



                                    <a style="font-size:12px;margin-top:-10px" href="@Url.Action("MotDePasseOubliee", "Compte")">Mot de passe oublié ?</a>

                                    <br />
                                    <a style="font-size:12px;margin-top:-14px" href="@Url.Action("ModifierMotDePasse", "Compte")">Modifier mon mot de passe</a>

                                </div>
                            </div>
                        </div>
                    </div>
                }
            </section>
        </div>
    </div>
    <div class="col-12 col-sm-12 col-md-1 col-lg-3"></div>
</div>






@*@section scripts{
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}*@

Autoveille/Views/Compte/Index.cshtml
@model  Autoveille.Models.ConcessionsModel
@{
    ViewBag.Title = "Connexion";
}

<h2>Liste commerces</h2>

<div class="col-xd-12  col-sm-12 col-md-12  col-lg-12" style="float: left">
        @if (Model == null || Model.ListConcessions == null || !Model.ListConcessions.Any())
        {
            <div class="alert alert-info">Aucune concession trouvée.</div>
        }
        else
        {
                  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <table class="table table-striped table-hover table-bordered">
                    <thead>
                    <tr> 
                        <th>Concession</th>
                    </tr>
                    </thead>
                    <tbody>

                    @foreach (var item in Model.ListConcessions.OrderBy(x => x.NomCommerce))
                    {
                        <tr style="vertical-align:bottom">
                            <td >
                                 @Html.ActionLink(item.NomCommerce,
                                    "Recherche","Home",
                                    new {aNoCommerce = item.NoCommerce},
                                    new {@class="basFieldset"}) 
                            </td>

                        </tr>
                    }
                    </tbody>
                </table>
            </div>
           
      
            @* 
            
            
            @(Html.C1().FlexGrid().Id("fGRCView").AutoGenerateColumns(false).AllowAddNew(true)
    .AllowSorting(true).CssClass("grid")
    .Columns(columns => columns
        .Add(c => c.Binding("CategoryID"))
        .Add(c => c.Binding("CategoryName"))
        .Add(c => c.Binding("Description").Width("500")))
    .Bind(
        ib => ib.Bind(Url.Action("GridReadCategory"))
    )
)*@
            
            
        }
</div>

Autoveille/Views/Compte/Logoff.cshtml
@{
    ViewBag.Title = "Logoff";
}

<h2>Logoff</h2>

Autoveille/Views/Compte/ModifierMotDePasse.cshtml
@{
    ViewBag.Title = "ModifierMotDePasse";
    Layout = "~/Views/Shared/_InitialLayout.cshtml";
}
<style>
    body {
        background-color: #fbbb29;
    }
</style>

<div class="row">
    <div class="col-12 col-sm-12 col-md-1 col-lg-3">
    </div>
    <div class="col-12 col-sm-12 col-md-10 col-lg-6">

        <div style="background-color:#fbbb29;padding-top:10px;padding-left:60px;padding-right:60px; height:350px">
            <div id="loginForm" style="margin: 0 auto;height:347px;">
                <div class="inputs" style="height:100%;">
                    <input class="changePwdInput" type="email" placeholder="Usager(Courriel)">  <br />
                    <input class="changePwdInput" type="password" placeholder="Ancien Mot de Passe">  <br />
                    <input class="changePwdInput" type="password" placeholder="Nouveau Mot de passe">  <br />
                    <input class="changePwdInput" type="password" placeholder="Confirmer nouveau mot de passe">  <br />
                    <div style="text-align:center;">
                        <input type="submit" class="btn btn-danger submitInput" value="Soumettre" data-toggle="modal" data-target="#annonceModal" onclick="changePassword()">
                    </div>
                </div>

            </div>
        </div>



    </div>

    <div class="col-12 col-sm-12 col-md-1 col-lg-3"></div>


</div>


<div id="annonceModal" class="modal modal-wide fade" role="dialog">
    <div class="modal-dialog oublieMotDePasse">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header" style="display:none;">
                <button type="button" class="close" data-dismiss="modal" onclick="removeBackdrop()">&times;</button>
                <h4 class="modal-title">Calendrier des rendez Vous</h4>
            </div>
            <div class="modal-body">
                <p style="font-weight:bold;font-size:1.5vw;">Votre mot de passe a été modifié </p>
                @*<span style="font-weight:bold;font-size:1vw;">Nous avons reçu votre demande </span> <br />*@
                <span>Tel que demandé , le mot de passe associé au compte prenomnom@sviceInternet.ca a été modifié </span> <br /> <br />
                <a href="@Url.Action("Connexion", "Compte")">Revenir à la page d'identification </a>
            </div>
            <div class="modal-footer" style="display:none;">
                <button type="button" class="btn btn-default" data-dismiss="modal" onclick="removeBackdrop()">Fermer</button>
            </div>
        </div>

    </div>
</div>


<script>
    function changePassword(newPassword) {
        $.ajax({
            url: '../Compte/ModifierMotDePasse',
            contentType: 'application/html; charset=utf-8',
            type: 'POST',
            data : json.stringify(newPassword)
            dataType: 'html',
            success: function (result) {
                $('.modal-body').modal("show");
            },
            error: function (xhr, status) {
                alert(status);
            }
        });
    }
</script>

Autoveille/Views/Compte/MotDePasseOubliee.cshtml
@{
    ViewBag.Title = "MotDePasseOubliee";
    Layout = "~/Views/Shared/_InitialLayout.cshtml";
}



<style>
    body {
        background-color: #fbbb29;
    }

</style>
<div class="row">
    <div class="col-12 col-sm-12 col-md-1 col-lg-3">
    </div>
    <div class="col-12 col-sm-12 col-md-10 col-lg-6">

        <div style="background-color:#fbbb29;padding-top:10px;padding-left:60px;padding-right:60px; height:350px">
            <div id="loginForm" style="margin: 0 auto;height:347px;">
                <div class="textBox" style="text-align:center;">
                    <span style="text-align: center;color:white;font-size:19px;text-align:center; font-weight:bold;"> Vous avez oublié votre mot de passe ? </span> <br /> <br />
                    <span style="text-align: center;color:white;font-size:19px;text-align:center;font-size:15px;">Saisissez votre courriel </span> <br />
                    <span style="text-align: center;color:white;font-size:19px;text-align:center;font-size:13px;"> lié à votre compte, et nous vous enverrons les instructions pour en créer un nouveau.</span> <br />
                </div>


                <br />
                <br />


                <div class="inputs">
                    <input class="emailInput" type="email" placeholder="Usager(Courriel)">  <br />
                    <div style="text-align:center;">
                        <input type="submit" class="btn btn-danger submitInput" value="Soumettre" data-toggle="modal" data-target="#annonceModal" onclick="sendPassword()">
                    </div>
                </div>

            </div>
        </div>



    </div>

    <div class="col-12 col-sm-12 col-md-1 col-lg-3"></div>


</div>

<!-- Modal -->
<div id="annonceModal" class="modal modal-wide fade" role="dialog">
    <div class="modal-dialog oublieMotDePasse">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header" style="display:none;">
                <button type="button" class="close" data-dismiss="modal" onclick="removeBackdrop()">&times;</button>
                <h4 class="modal-title">Calendrier des rendez Vous</h4>
            </div>
            <div class="modal-body">
                <p style="font-weight:bold;font-size:1.5vw;">Réinitialiser le mot de passe </p>
                <span style="font-weight:bold;font-size:1vw;">Nous avons reçu votre demande </span> <br />
                <span>Un lien pour réinitialiser votre mot de passe a été envoyé par courriel à l'adresse renomnom@sviceInternet.ca</span> <br /> <br />
                <a href="@Url.Action("Connexion", "Compte")">Revenir à la page d'identification </a>
            </div>
            <div class="modal-footer" style="display:none;">
                <button type="button" class="btn btn-default" data-dismiss="modal" onclick="removeBackdrop()">Fermer</button>
            </div>
        </div>

    </div>
</div>

<script>

    function sendPassword() {
        $.ajax({
            url: '../Compte/sendPassword',
            contentType: 'application/html; charset=utf-8',
            type: 'GET',
            dataType: 'html',
            success: function (result) {
                $('.modal-body').modal("show");
            },
            error: function (xhr, status) {
                alert(status);
            }
        });
    }
</script>